Repository MetroStar/comet, pull requests merged in 2023-05, with the labels that each got.

#42 War-51: New Prose component
  packages/comet/src/components/index.ts
  packages/comet/src/components/prose/index.ts
  packages/comet/src/components/prose/prose.stories.tsx
  packages/comet/src/components/prose/prose.test.tsx
  packages/comet/src/components/prose/prose.tsx
Labels: enhancement

#44 WAR-26: Add automated NPM publish
  .github/workflows/publish-package.yaml
  package.json
Labels: enhancement

#45 Misc component fixes
  packages/comet-uswds/src/components/card/card.stories.tsx
  packages/comet-uswds/src/components/card/card.test.tsx
  packages/comet-uswds/src/components/card/card.tsx
  packages/comet-uswds/src/components/file-input/file-input.tsx
Labels: bug, enhancement

#46 Release: 1.0.1
  packages/comet-uswds/package.json
Labels: release
