Repository MetroStar/comet, pull requests merged in 2023-06, with the labels that each got.

#30 WAR-20: Add Memorable Date to WarpSpeed
  packages/comet-uswds/src/components/index.ts
  packages/comet-uswds/src/components/memorable-date/index.ts
  packages/comet-uswds/src/components/memorable-date/memorable-date.stories.tsx
  packages/comet-uswds/src/components/memorable-date/memorable-date.test.tsx
  packages/comet-uswds/src/components/memorable-date/memorable-date.tsx
Labels: enhancement

#47 CSG-632: Final Cleanup/Review of Comet Projects
  CONTRIBUTING.md
  README.md
  RELEASING.md
  images/comet-logo.png
  package-lock.json
  package.json
Labels: documentation

#49 CSG-718: Add Custom Spinner component to Comet Extras
  packages/comet-extras/src/components/index.ts
  packages/comet-extras/src/components/spinner/index.ts
  packages/comet-extras/src/components/spinner/spinner.stories.tsx
  packages/comet-extras/src/components/spinner/spinner.style.css
  packages/comet-extras/src/components/spinner/spinner.test.tsx
  packages/comet-extras/src/components/spinner/spinner.tsx
Labels: enhancement

#51 CSG-724: Fix Styling Issues on Comet USWDS components
  .storybook/manager.js
  .storybook/theme.js
  images/comet-logo-sm.png
  packages/comet-uswds/src/components/button-group/button-group.stories.tsx
  packages/comet-uswds/src/components/button-group/button-group.test.tsx
  packages/comet-uswds/src/components/button-group/button-group.tsx
Labels: bug, documentation, enhancement

#54 CSG-729: Add Automated Accessibility Testing to Comet
  jest-setup.js
  jest.config.js
  package-lock.json
  package.json
  packages/comet-extras/src/components/spinner/spinner.test.tsx
  packages/comet-extras/src/components/tabs/tabs.test.tsx
  packages/comet-uswds/src/components/accordion/accordion.test.tsx
  packages/comet-uswds/src/components/alert/alert.test.tsx
  packages/comet-uswds/src/components/banner/banner.test.tsx
  packages/comet-uswds/src/components/breadcrumb/breadcrumb.test.tsx
  packages/comet-uswds/src/components/button-group/button-group.test.tsx
  packages/comet-uswds/src/components/button/button.test.tsx
  packages/comet-uswds/src/components/card/card.test.tsx
  packages/comet-uswds/src/components/character-count/character-count.test.tsx
  packages/comet-uswds/src/components/checkbox/checkbox.test.tsx
  packages/comet-uswds/src/components/combo-box/combo-box.test.tsx
  packages/comet-uswds/src/components/date-picker/date-picker.test.tsx
  packages/comet-uswds/src/components/date-range-picker/date-range-picker.test.tsx
  packages/comet-uswds/src/components/dropdown/dropdown.test.tsx
  packages/comet-uswds/src/components/error-messages/error-messages.test.tsx
  packages/comet-uswds/src/components/file-input/file-input.test.tsx
  packages/comet-uswds/src/components/footer/footer.test.tsx
  packages/comet-uswds/src/components/footer/footer.tsx
  packages/comet-uswds/src/components/form-group/form-group.test.tsx
  packages/comet-uswds/src/components/form/form.test.tsx
  packages/comet-uswds/src/components/header/header.test.tsx
  packages/comet-uswds/src/components/icon/icon.test.tsx
  packages/comet-uswds/src/components/label/label.test.tsx
  packages/comet-uswds/src/components/list/list.test.tsx
  packages/comet-uswds/src/components/memorable-date/memorable-date.test.tsx
  packages/comet-uswds/src/components/modal/modal.test.tsx
  packages/comet-uswds/src/components/pagination/pagination.test.tsx
  packages/comet-uswds/src/components/process-list/process-list.test.tsx
  packages/comet-uswds/src/components/prose/prose.test.tsx
  packages/comet-uswds/src/components/radio-button/radio-button.test.tsx
  packages/comet-uswds/src/components/range-slider/range-slider.test.tsx
  packages/comet-uswds/src/components/search/search.test.tsx
  packages/comet-uswds/src/components/side-navigation/side-navigation.test.tsx
  packages/comet-uswds/src/components/site-alert/site-alert.test.tsx
  packages/comet-uswds/src/components/step-indicator/step-indicator.test.tsx
  packages/comet-uswds/src/components/summary-box/summary-box.test.tsx
  packages/comet-uswds/src/components/table/table.test.tsx
  packages/comet-uswds/src/components/tag/tag.test.tsx
  packages/comet-uswds/src/components/text-area/text-area.test.tsx
  packages/comet-uswds/src/components/text-input/text-input.test.tsx
  packages/comet-uswds/src/components/time-picker/time-picker.test.tsx
  packages/comet-uswds/src/components/tooltip/tooltip.test.tsx
Labels: enhancement, refactor

#55 CSG-738: Upgrade Comet to USWDS 3.5.0
  package-lock.json
  packages/comet-uswds/package.json
Labels: dependencies

#57 Release: 1.3.0
  package-lock.json
  packages/comet-uswds/package.json
Labels: release

#59 CSG-770: Fix Comet USWDS Table Accessibility issue
  packages/comet-data-viz/src/components/bar-graph/bar-graph.stories.tsx
  packages/comet-uswds/src/components/table/table.tsx
Labels: bug

#60 Release: 1.3.1
  package-lock.json
  packages/comet-uswds/package.json
Labels: release
