Repository MetroStar/comet, pull requests merged in 2024-12, with the labels that each got.

#295 Vite 6.0.2 Update with Supporting Updates for Storybook and React
  .gitignore
  package-lock.json
  package.json
  packages/comet-data-viz/tsconfig.json
  packages/comet-extras/tsconfig.json
  packages/comet-uswds/tsconfig.json
  tsconfig.json
Labels: dependencies

#297 Upgrade storybook to 8.4.7
  package-lock.json
  package.json
Labels: dependencies

#299 Update for Node 20 as base
  .github/workflows/build-and-deploy.yaml
  .github/workflows/code-quality.yaml
  .github/workflows/publish-package.yaml
Labels: ci

#298 Upgrade to React 19
  .github/dependabot.yml
  package-lock.json
  package.json
  packages/comet-cli/tsconfig.json
  packages/comet-data-viz/package.json
  packages/comet-extras/package.json
  packages/comet-extras/src/components/spinner/spinner.figma.tsx
  packages/comet-extras/src/components/spinner/spinner.tsx
  packages/comet-uswds/package.json
  packages/comet-uswds/src/components/button/button.tsx
  packages/comet-uswds/src/components/character-count/character-count.tsx
  packages/comet-uswds/src/components/checkbox/checkbox.tsx
  packages/comet-uswds/src/components/combo-box/combo-box.tsx
  packages/comet-uswds/src/components/date-picker/date-picker.tsx
  packages/comet-uswds/src/components/file-input/file-input.test.tsx
  packages/comet-uswds/src/components/file-input/file-input.tsx
  packages/comet-uswds/src/components/form-group/form-group.tsx
  packages/comet-uswds/src/components/form/form.tsx
  packages/comet-uswds/src/components/label/label.tsx
  packages/comet-uswds/src/components/modal/modal.test.tsx
  packages/comet-uswds/src/components/pagination/pagination.tsx
  packages/comet-uswds/src/components/prose/prose.tsx
  packages/comet-uswds/src/components/radio-button/radio-button.tsx
  packages/comet-uswds/src/components/range-slider/range-slider.tsx
  packages/comet-uswds/src/components/search/search.tsx
  packages/comet-uswds/src/components/select/select.tsx
  packages/comet-uswds/src/components/side-navigation/side-navigation.stories.tsx
  packages/comet-uswds/src/components/side-navigation/side-navigation.test.tsx
  packages/comet-uswds/src/components/side-navigation/side-navigation.tsx
  packages/comet-uswds/src/components/text-area/text-area.tsx
  packages/comet-uswds/src/components/text-input/text-input.tsx
  packages/comet-uswds/src/components/time-picker/time-picker.tsx
Labels: enhancement, refactor, dependencies

#302 Release: 3.7.0
  package-lock.json
  packages/comet-data-viz/package.json
  packages/comet-extras/package.json
  packages/comet-uswds/package.json
Labels: release

#304 Release: 3.7.1
  package-lock.json
  packages/comet-uswds/package.json
Labels: release

#305 Fix: Fail Pipeline when Lint or Format issues
  .github/workflows/code-quality.yaml
  package.json
  packages/comet-extras/src/components/spinner/spinner.style.css
Labels: ci

#308 Remove React Dependencies from Packages
  package-lock.json
  packages/comet-data-viz/package.json
  packages/comet-extras/package.json
  packages/comet-uswds/package.json
Labels: dependencies

#310 Release: 1.6.0 (Comet Extras)
  package-lock.json
  packages/comet-extras/package.json
Labels: release
