Repository MetroStar/comet, pull requests merged in 2025-06, with the labels that each got.

#366 Storybook Vitest Addon
  .github/workflows/code-quality.yaml
  .storybook/main.js
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  CONTRIBUTING.md
  package-lock.json
  package.json
  packages/comet-extras/src/components/data-table/data-table.test.tsx
  packages/comet-extras/src/components/spinner/spinner.test.tsx
  packages/comet-extras/src/components/tabs/tabs.test.tsx
  packages/comet-extras/src/components/toast/toast.test.tsx
  packages/comet-extras/src/components/toggle/toggle.test.tsx
  packages/comet-uswds/src/components/accordion/accordion.test.tsx
  packages/comet-uswds/src/components/alert/alert.test.tsx
  packages/comet-uswds/src/components/banner/banner.test.tsx
  packages/comet-uswds/src/components/breadcrumb/breadcrumb.test.tsx
  packages/comet-uswds/src/components/button-group/button-group.test.tsx
  packages/comet-uswds/src/components/button/button.test.tsx
  packages/comet-uswds/src/components/card/card.test.tsx
  packages/comet-uswds/src/components/character-count/character-count.test.tsx
  packages/comet-uswds/src/components/checkbox/checkbox.test.tsx
  packages/comet-uswds/src/components/combo-box/combo-box.test.tsx
  packages/comet-uswds/src/components/date-picker/date-picker.test.tsx
  packages/comet-uswds/src/components/date-range-picker/date-range-picker.test.tsx
  packages/comet-uswds/src/components/error-messages/error-messages.test.tsx
  packages/comet-uswds/src/components/file-input/file-input.test.tsx
  packages/comet-uswds/src/components/form-group/form-group.test.tsx
  packages/comet-uswds/src/components/form/form.test.tsx
  packages/comet-uswds/src/components/helper-text/helper-text.test.tsx
  packages/comet-uswds/src/components/icon/icon.test.tsx
  packages/comet-uswds/src/components/in-page-navigation/in-page-navigation.test.tsx
  packages/comet-uswds/src/components/label/label.test.tsx
  packages/comet-uswds/src/components/language-selector/language-selector.test.tsx
  packages/comet-uswds/src/components/list/list.test.tsx
  packages/comet-uswds/src/components/memorable-date/memorable-date.test.tsx
  packages/comet-uswds/src/components/modal/modal.test.tsx
  packages/comet-uswds/src/components/pagination/pagination.test.tsx
  packages/comet-uswds/src/components/process-list/process-list.test.tsx
  packages/comet-uswds/src/components/prose/prose.test.tsx
  packages/comet-uswds/src/components/radio-button/radio-button.test.tsx
  packages/comet-uswds/src/components/range-slider/range-slider.test.tsx
  packages/comet-uswds/src/components/search/search.test.tsx
  packages/comet-uswds/src/components/select/select.test.tsx
  packages/comet-uswds/src/components/side-navigation/side-navigation.test.tsx
  packages/comet-uswds/src/components/site-alert/site-alert.test.tsx
  packages/comet-uswds/src/components/step-indicator/step-indicator.test.tsx
  packages/comet-uswds/src/components/summary-box/summary-box.test.tsx
  packages/comet-uswds/src/components/table/table.stories.tsx
  packages/comet-uswds/src/components/table/table.test.tsx
  packages/comet-uswds/src/components/tag/tag.test.tsx
  packages/comet-uswds/src/components/text-area/text-area.stories.tsx
  packages/comet-uswds/src/components/text-area/text-area.test.tsx
  packages/comet-uswds/src/components/text-input/text-input.stories.tsx
  packages/comet-uswds/src/components/text-input/text-input.test.tsx
  packages/comet-uswds/src/components/time-picker/time-picker.test.tsx
  packages/comet-uswds/src/components/tooltip/tooltip.test.tsx
  vite.config.js
  vitest.setup.ts
  vitest.shims.d.ts
Labels: documentation, dependencies, ci

#368 UI Overhaul/Changes for Spinner Component
  packages/comet-extras/src/components/spinner/spinner.figma.tsx
  packages/comet-extras/src/components/spinner/spinner.stories.tsx
  packages/comet-extras/src/components/spinner/spinner.style.css
  packages/comet-extras/src/components/spinner/spinner.test.tsx
  packages/comet-extras/src/components/spinner/spinner.tsx
Labels: enhancement

#369 Comet Extras Release: 1.7.2
  package-lock.json
  packages/comet-extras/package.json
Labels: release

#370 Misc Enhancements
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
Labels: enhancement, dependencies
